name: Post welcome comment
run-name: ${{ github.actor }} is running it

on:
  pull_request:
    types: [opened]
  push:
    
permissions:
  pull-requests: write

jobs:

  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to laurence`s repository"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          
