name: Post welcome comment
run-name: ${{ github.actor }} is running it

on:
  workflow_dispatch:  # Manual run event
  pull_request:
    types: [opened]
  push:

permissions:
  pull-requests: write

jobs:
  build:
    name: Job Number One
    runs-on: ubuntu-latest
    steps:
      - name: What is my secret?
        run: echo ${{ secrets.MY_OWN_SECRET}} 
      - name: Dump Env Context
        run: echo ${{ toJson(env) }}
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump Step Context
        env:
          STEP_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEP_CONTEXT"
      - name: Dump Runner Context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - run: gh pr comment $PR_URL --body "Welcome to laurence's repository"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
